const programs = [
  'Bachelor of Elementary Education (BEED)',
  'Bachelor of Early Childhood Education (BCED)',
  'Bachelor of Special Needs Education (BSNED)',
  'Bachelor Physical Education (BPED)',
  'Bachelor of Technology and Livelihood Education major in Home Economics (BTLED)',
  'Bachelor of Technology and Livelihood Education major in Industrial Arts (BTLED)',
  'Bachelor of Secondary Education major in English (BSED English)',
  'Bachelor of Secondary Education major in Filipino (BSED Filipino)',
  'Bachelor of Secondary Education major in Mathematics (BSED Mathematics)',
  'Bachelor of Secondary Education major in Science (BSED Science)',
  'Bachelor of Science in Agribusiness Management (BSAM)',
  'Bachelor of Science in Agriculture major in Horticulture (BSA)',
  'Bachelor of Science in Agriculture major in Animal Science (BSA)',
  'Bachelor of Science in Agriculture major in Crop Science (BSA)',
  'Bachelor of Science in Biology (BSBio)',
  'Bachelor of Science in Biology major in Animal Biology (BSBio)',
  'Bachelor of Science in Biology major in Ecology (BSBio)',
  'Bachelor of Science in Environmental Science (BSES)',
  'Bachelor in Industrial Technology Management major in Automotive Technology (BITM)',
  'Bachelor of Science in Civil Engineering (BSCE)',
  'Bachelor of Science in Information Technology (BSIT)',
  'Bachelor of Science in Mathematics (BSMath)',
  'Bachelor of Science in Mathematics with Research Statistics (BSMath)',
  'Bachelor of Science in Nursing (BSN)',
  'Bachelor of Science in Criminology (BSC)',
  'Bachelor of Science in Business Administration major of Financial Management (BSBA)',
  'Bachelor of Science in Hospitality Management (BSHM)',
  'Bachelor of Arts Political Science (BA PolSci)',
  'Bachelor of Science in Development Communication (BSDevCom)',
  'Bachelor of Science in Psychology (BS Psychology)'
];

export default programs;
