# Generated by Django 5.2.5 on 2025-09-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='program',
        ),
    ]
