# Generated by Django 5.2.5 on 2025-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_alumni_graduation_year_remove_alumni_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programhead',
            old_name='department',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='programhead',
            old_name='full_name',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='programhead',
            name='contact',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programhead',
            name='faculty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programhead',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programhead',
            name='mi',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='programhead',
            name='program',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
