# Generated by Django 5.2.5 on 2025-09-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_department_programhead_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
