# Generated by Django 5.2.5 on 2025-09-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alumni_add_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='consent',
        ),
    ]
