# Generated by Django 5.2.5 on 2025-09-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alumni_verification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='verification_image',
        ),
    ]
