# Generated by Django 5.2.5 on 2025-09-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_alumni_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('year_graduated', models.CharField(blank=True, max_length=8)),
                ('course_program', models.CharField(blank=True, max_length=255)),
                ('student_number', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.CharField(blank=True, max_length=6)),
                ('birth_month', models.CharField(blank=True, max_length=16)),
                ('birth_day', models.CharField(blank=True, max_length=4)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('home_address', models.TextField(blank=True)),
                ('telephone_number', models.CharField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_job_position', models.CharField(blank=True, max_length=255)),
                ('company_affiliation', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('approximate_monthly_salary', models.CharField(blank=True, max_length=64)),
                ('employed_after_graduation', models.CharField(blank=True, max_length=16)),
                ('job_difficulties', models.JSONField(blank=True, default=list)),
                ('employment_source', models.CharField(blank=True, max_length=255)),
                ('jobs_related_to_experience', models.CharField(blank=True, max_length=16)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('has_been_promoted', models.CharField(blank=True, max_length=16)),
                ('work_performance_rating', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='users.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('date_employed', models.CharField(blank=True, max_length=32)),
                ('position_and_status', models.CharField(blank=True, max_length=255)),
                ('monthly_salary_range', models.CharField(blank=True, max_length=64)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='users.alumnisurvey')),
            ],
        ),
        migrations.CreateModel(
            name='SelfEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('nature_of_business', models.CharField(blank=True, max_length=255)),
                ('role_in_business', models.CharField(blank=True, max_length=255)),
                ('monthly_profit', models.CharField(blank=True, max_length=64)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=50)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_employment', to='users.alumnisurvey')),
            ],
        ),
    ]
