# Generated by Django 5.2.5 on 2025-09-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_alumni_program_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfemployment',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='selfemployment',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='selfemployment',
            name='business_phone',
        ),
        migrations.RemoveField(
            model_name='selfemployment',
            name='monthly_profit',
        ),
        migrations.RemoveField(
            model_name='selfemployment',
            name='nature_of_business',
        ),
        migrations.RemoveField(
            model_name='selfemployment',
            name='role_in_business',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('nature_of_business', models.CharField(blank=True, max_length=255)),
                ('role_in_business', models.CharField(blank=True, max_length=255)),
                ('monthly_profit', models.CharField(blank=True, max_length=64)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=50)),
                ('program_head', models.ForeignKey(db_column='program_head_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_programs', to='users.programhead')),
            ],
            options={
                'ordering': ['program_name'],
            },
        ),
    ]
