# Generated by Django 5.2.5 on 2025-09-19 16:02

from django.db import migrations


def _safe_remove_columns(apps, schema_editor):
    """Conditionally drop legacy columns from the users_program table.

    This migration was failing when the `users_program` table did not exist
    in the database (different environment or missing initial migrations).
    Instead of unconditionally removing fields, we check information_schema
    for the table and each column before attempting the ALTER TABLE DROP COLUMN
    statements. This keeps the migration safe to run in environments where
    the table or columns are already absent.
    """
    conn = schema_editor.connection
    cursor = conn.cursor()

    # Check whether users_program exists
    cursor.execute("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = 'users_program'")
    table_exists = cursor.fetchone()[0] > 0
    if not table_exists:
        # Nothing to do; table is missing
        return

    # List of legacy columns to drop if present
    legacy_columns = [
        'business_address',
        'business_name',
        'business_phone',
        'monthly_profit',
        'nature_of_business',
        'role_in_business',
    ]

    for col in legacy_columns:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'users_program' AND column_name = %s",
            (col,)
        )
        if cursor.fetchone()[0] > 0:
            # drop the column
            cursor.execute(f"ALTER TABLE `users_program` DROP COLUMN `{col}`")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_users_migrations'),
    ]

    operations = [
        migrations.RunPython(_safe_remove_columns, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelTable(
            name='program',
            table='users_program',
        ),
    ]
