# Generated by Django 5.2.5 on 2025-09-19 16:06

from django.db import migrations


def _safe_remove_legacy_columns(apps, schema_editor):
    conn = schema_editor.connection
    cursor = conn.cursor()

    # check table exists
    cursor.execute("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = 'users_program'")
    table_exists = cursor.fetchone()[0] > 0
    if not table_exists:
        return

    legacy_columns = [
        'business_address',
        'business_name',
        'business_phone',
        'monthly_profit',
        'nature_of_business',
        'role_in_business',
    ]

    for col in legacy_columns:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'users_program' AND column_name = %s",
            (col,)
        )
        if cursor.fetchone()[0] > 0:
            cursor.execute(f"ALTER TABLE `users_program` DROP COLUMN `{col}`")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_program_business_address_and_more'),
    ]

    operations = [
        migrations.RunPython(_safe_remove_legacy_columns, reverse_code=migrations.RunPython.noop),
    ]
