# Generated by Django 5.2.5 on 2025-09-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_program_business_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='program',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='business_phone',
        ),
        migrations.RemoveField(
            model_name='program',
            name='monthly_profit',
        ),
        migrations.RemoveField(
            model_name='program',
            name='nature_of_business',
        ),
        migrations.RemoveField(
            model_name='program',
            name='role_in_business',
        ),
    ]
