# Generated by ChatGPT - migration to add image field to ProgramHead
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_selfemployment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='programhead',
            name='image',
            field=models.ImageField(upload_to='programhead_images/', null=True, blank=True),
        ),
    ]
