# Generated by Django 5.2.5 on 2025-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_programhead_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programhead',
            name='image',
        ),
        migrations.AlterField(
            model_name='selfemployment',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='selfemployment',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='selfemployment',
            name='business_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='selfemployment',
            name='monthly_profit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='selfemployment',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='selfemployment',
            name='role_in_business',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
