# Generated by Django 5.2.5 on 2025-10-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_programhead_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='year_graduated',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
