# Generated by Django 5.2.5 on 2025-10-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alumni_year_graduated_programhead_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfemployment',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_employment', to='users.alumnisurvey'),
        ),
    ]
