# Generated by Django 5.2.5 on 2025-10-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_admin_add_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programhead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programhead_images/'),
        ),
    ]
