# Generated by Django 5.2.5 on 2025-11-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_notification_delete_selfemployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnisurvey',
            name='has_own_business',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SelfEmployment',
        ),
    ]
