# Generated by Django 5.2.5 on 2025-11-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alumnisurvey_has_own_business_delete_selfemployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnisurvey',
            name='has_own_business',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
    ]
